import fs from 'node:fs/promises';
const zipPath = process.argv[2] || 'site.zip';
const token = process.env.NETLIFY_AUTH_TOKEN;
const site = process.env.NETLIFY_SITE_ID;
if (!token || !site) throw new Error('Missing Netlify backup secrets');
const body = await fs.readFile(zipPath);
const res = await fetch(`https://api.netlify.com/api/v1/sites/${site}/deploys`, { method:'POST', headers:{ Authorization:`Bearer ${token}`, 'Content-Type':'application/zip' }, body });
const data = await res.json().catch(()=>({}));
if (!res.ok) throw new Error(`Netlify deploy failed ${res.status}: ${JSON.stringify(data)}`);
console.log(`deploy_url=${data.ssl_url || data.deploy_ssl_url || data.url}`);
