import fs from 'node:fs/promises';
import https from 'node:https';
const zipPath = process.argv[2] || 'site.zip';
const token = process.env.NETLIFY_AUTH_TOKEN;
const siteId = process.env.NETLIFY_SITE_ID;
if (!token || !siteId) throw new Error('Missing NETLIFY_AUTH_TOKEN or NETLIFY_SITE_ID');
const data = await fs.readFile(zipPath);
const options = { method:'POST', hostname:'api.netlify.com', path:`/api/v1/sites/${siteId}/deploys`, headers:{ Authorization:`Bearer ${token}`, 'Content-Type':'application/zip', 'Content-Length':data.length } };
const body = await new Promise((resolve,reject)=>{const req=https.request(options,res=>{let chunks='';res.setEncoding('utf8');res.on('data',d=>chunks+=d);res.on('end',()=>res.statusCode>=200&&res.statusCode<300?resolve(chunks):reject(new Error(`Netlify ${res.statusCode}: ${chunks}`)));});req.on('error',reject);req.end(data);});
const json = JSON.parse(body);
const url = json.ssl_url || json.deploy_ssl_url || json.url;
console.log(`deploy_url=${url}`);
await fs.appendFile(process.env.GITHUB_OUTPUT || '/dev/null', `deploy_url=${url}\n`);
