import fs from 'node:fs/promises';
import path from 'node:path';
import {
  AUTO_DIR,
  GAMES_DIR,
  PUBLIC_DIR,
  callGemini,
  deterministicPick,
  ensureFolders,
  escapeHtml,
  extractGameHtml,
  injectSeo,
  isoDate,
  parseJsonLoose,
  readJson,
  slugify,
  validateGameHtml,
  writeJson
} from './common.mjs';

const THEMES = [
  'a floating city powered by musical energy',
  'a tiny robot repairing a shifting space garden',
  'a dream library where rooms rearrange themselves',
  'a neon delivery race through impossible architecture',
  'a friendly creature ecosystem that must be balanced',
  'a time-loop puzzle arena with changing gravity',
  'an underwater research station built from glowing coral',
  'a sky-island factory with conveyor-belt puzzles',
  'a magical map that redraws itself while the player explores',
  'a cosmic sports tournament using energy orbs',
  'a storm-chasing glider collecting weather fragments',
  'a miniature city where the player controls traffic and power'
];

const MECHANICS = [
  'action strategy with waves, upgrades, and a boss',
  'physics puzzle platformer with level progression',
  'top-down exploration with quests and crafting',
  'arcade management game with combo systems',
  'tower-defense inspired game without realistic weapons',
  'endless runner with branching routes and missions',
  'real-time puzzle game with chained abilities',
  'arena survival game using harmless energy pulses'
];

const manifestFile = path.join(PUBLIC_DIR, 'games.json');
const date = isoDate();

await ensureFolders();
const manifest = await readJson(manifestFile, []);
const previous = manifest.slice(0, 12).map(game => `${game.title} — ${game.description}`).join('\n');
const theme = deterministicPick(THEMES, `${date}-theme-${manifest.length}`);
const mechanic = deterministicPick(MECHANICS, `${date}-mechanic-${manifest.length}`);

const planPrompt = `
You are the lead designer of a browser-game studio. Plan ONE original, substantial, polished game for Amit's daily game website.

Seed date: ${date}
Theme seed: ${theme}
Mechanic seed: ${mechanic}
Recent games to avoid repeating:
${previous || '(none yet)'}

Rules:
- Original concept only. Do not use copyrighted characters, brands, logos, music, or copied game names.
- Suitable for all ages. No gore, realistic weapons, gambling, paid mechanics, chat, login, or external services.
- The final game must work as one self-contained HTML file, offline, on desktop and mobile.
- It must feel bigger than a tiny demo: title screen, tutorial, at least 8 stages/waves/missions, upgrades or progression, score, pause, restart, sound toggle, saved progress, win/lose states, and a replay reason.
- Use Canvas 2D, generated shapes, particles, gradients, and Web Audio. No external images, fonts, libraries, or network calls.

Return strict JSON with these keys only:
{
  "title": "short English title",
  "slug": "lowercase-ascii-slug",
  "description": "one sentence",
  "genre": "genre",
  "coreLoop": "clear core loop",
  "systems": ["at least 8 concrete systems"],
  "stages": "how progression reaches at least 8 stages",
  "artDirection": "visual direction",
  "specialTwist": "the memorable twist"
}`;

console.log('1/4 Planning a new game...');
const planResponse = await callGemini({ prompt: planPrompt, json: true, temperature: 1.0, maxOutputTokens: 4096 });
const plan = parseJsonLoose(planResponse.text);
plan.title = String(plan.title || `Amit Game ${date}`).slice(0, 80);
plan.slug = slugify(plan.slug || plan.title);
plan.description = String(plan.description || 'An original browser game generated by Amit’s game factory.').slice(0, 220);

let slug = `${date}-${plan.slug}`;
if (manifest.some(game => game.slug === slug)) slug = `${slug}-${manifest.length + 1}`;
const gameDir = path.join(GAMES_DIR, slug);
await fs.mkdir(gameDir, { recursive: true });

const buildPrompt = `
You are a senior HTML5 game engineer, UI designer, sound designer, and QA engineer working together.
Build the complete game described by this approved plan:
${JSON.stringify(plan, null, 2)}

Non-negotiable technical requirements:
- Return exactly one complete self-contained HTML document between the markers shown below.
- The file must contain all CSS and JavaScript inline and be at least 18,000 characters of meaningful code.
- Canvas 2D game with requestAnimationFrame and delta-time handling.
- Responsive desktop and mobile layout; keyboard plus visible touch controls using pointer events.
- Strong presentation: animated title screen, HUD, readable tutorial, pause overlay, settings/sound button, stage transitions, particles, screen shake used gently, and polished menus.
- At least 8 meaningful stages/waves/missions, a final challenge or boss-like encounter, upgrades/progression, score/combo, localStorage save, restart, win and lose states.
- Audio must be generated only with Web Audio and must begin only after user interaction.
- No external files, URLs, fetch, imports, libraries, iframes, copyrighted names/assets, realistic weapons, gore, gambling, ads, logins, or purchases.
- Avoid placeholder text and unfinished TODOs.
- Keep all code browser-safe and syntax-correct. Do not use JavaScript modules.
- Include a small footer that says: “Created by Amit’s Daily Game Factory”.

Output format, with no markdown fences and no explanation:
===GAME_HTML_START===
<!doctype html>
...the entire game...
===GAME_HTML_END===`;

console.log('2/4 Building the complete game...');
let buildResponse = await callGemini({ prompt: buildPrompt, temperature: 0.72, maxOutputTokens: 32768 });
let html = extractGameHtml(buildResponse.text);
let errors = validateGameHtml(html);

const repairAttempts = Math.max(0, Math.min(3, Number(process.env.QUALITY_REPAIR_ATTEMPTS || 2)));
for (let attempt = 1; errors.length && attempt <= repairAttempts; attempt += 1) {
  console.log(`3/4 Repair pass ${attempt}: ${errors.join(' | ')}`);
  const repairPrompt = `
You are the final QA and repair engineer. Correct the complete HTML game below.

Validation failures:
${errors.map((error, index) => `${index + 1}. ${error}`).join('\n')}

Repair every failure without removing features or shrinking the game. Keep it original, self-contained, offline, family-friendly, responsive, and polished. Return the entire corrected HTML only inside these markers, with no markdown or explanation:
===GAME_HTML_START===
[complete corrected HTML]
===GAME_HTML_END===

CURRENT HTML:
${html}`;
  const repairResponse = await callGemini({ prompt: repairPrompt, temperature: 0.25, maxOutputTokens: 32768 });
  html = extractGameHtml(repairResponse.text);
  errors = validateGameHtml(html);
}

if (errors.length) {
  await fs.writeFile(path.join(AUTO_DIR, 'last-invalid-game.html'), html, 'utf8');
  throw new Error(`Generated game failed validation: ${errors.join(' | ')}`);
}

const siteUrl = (process.env.SITE_URL || '').replace(/\/$/, '');
const gameUrl = siteUrl ? `${siteUrl}/games/${slug}/` : `/games/${slug}/`;
html = injectSeo(html, { title: plan.title, description: plan.description, canonicalUrl: siteUrl ? gameUrl : '' });
await fs.writeFile(path.join(gameDir, 'index.html'), html, 'utf8');

const entry = {
  title: plan.title,
  slug,
  description: plan.description,
  genre: String(plan.genre || 'Browser game'),
  date,
  url: `/games/${slug}/`,
  createdAt: new Date().toISOString(),
  generatorModel: buildResponse.model
};
const updatedManifest = [entry, ...manifest.filter(game => game.slug !== slug)];
await writeJson(manifestFile, updatedManifest);
await writeJson(path.join(AUTO_DIR, 'latest-game.json'), { ...entry, absoluteUrl: gameUrl, plan });

const cards = updatedManifest.map((game, index) => `
<a class="card" href="${escapeHtml(game.url)}" style="--delay:${Math.min(index, 12) * 45}ms">
  <div class="card-top"><span>${escapeHtml(game.genre || 'Game')}</span><time>${escapeHtml(game.date || '')}</time></div>
  <h2>${escapeHtml(game.title)}</h2>
  <p>${escapeHtml(game.description)}</p>
  <strong>PLAY NOW →</strong>
</a>`).join('\n');

const gallery = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="description" content="A new original browser game generated by Amit's automated game studio.">
  <title>Amit's Daily Game Factory</title>
  <style>
    :root{color-scheme:dark;--bg:#060814;--panel:#10162b;--text:#f5f7ff;--muted:#a9b3d6;--line:#263052;--glow:#7df9ff}
    *{box-sizing:border-box}body{margin:0;min-height:100vh;font-family:Inter,system-ui,Segoe UI,sans-serif;background:radial-gradient(circle at 15% 0,#18245a 0,transparent 34%),radial-gradient(circle at 90% 20%,#42145c 0,transparent 30%),var(--bg);color:var(--text)}
    .wrap{width:min(1180px,calc(100% - 32px));margin:auto;padding:72px 0}.badge{display:inline-flex;padding:8px 12px;border:1px solid #3b4775;border-radius:999px;color:var(--glow);background:#0d1430cc;font-weight:800;letter-spacing:.08em;font-size:.76rem}h1{font-size:clamp(2.5rem,8vw,6.8rem);line-height:.88;margin:22px 0 20px;max-width:900px;letter-spacing:-.065em}header p{max-width:680px;color:var(--muted);font-size:1.08rem;line-height:1.7}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:18px;margin-top:44px}.card{animation:rise .6s both;animation-delay:var(--delay);display:flex;min-height:260px;flex-direction:column;padding:24px;text-decoration:none;color:inherit;border:1px solid var(--line);border-radius:24px;background:linear-gradient(145deg,#131a34e8,#090d1ee8);box-shadow:0 18px 55px #0006;transition:.2s transform,.2s border-color}.card:hover{transform:translateY(-6px);border-color:#7690f0}.card-top{display:flex;justify-content:space-between;gap:10px;color:#8996c4;font-size:.78rem;text-transform:uppercase;letter-spacing:.08em}.card h2{font-size:1.65rem;margin:30px 0 10px}.card p{color:var(--muted);line-height:1.55;margin:0 0 24px}.card strong{margin-top:auto;color:var(--glow);font-size:.86rem;letter-spacing:.08em}.empty{padding:30px;border:1px dashed var(--line);border-radius:20px;color:var(--muted)}footer{margin-top:58px;color:#7180b2;font-size:.85rem}@keyframes rise{from{opacity:0;transform:translateY(18px)}to{opacity:1;transform:none}}
  </style>
</head>
<body><main class="wrap"><header><span class="badge">AUTOMATED GAME STUDIO</span><h1>Amit's Daily Game Factory</h1><p>A growing collection of original games. The studio plans, codes, checks, publishes, and emails a new game automatically.</p></header><section class="grid">${cards || '<div class="empty">The first generated game will appear here.</div>'}</section><footer>Built and maintained by Amit's automation.</footer></main></body></html>`;
await fs.writeFile(path.join(PUBLIC_DIR, 'index.html'), gallery, 'utf8');

const robots = `User-agent: *\nAllow: /\n${siteUrl ? `Sitemap: ${siteUrl}/sitemap.xml\n` : ''}`;
await fs.writeFile(path.join(PUBLIC_DIR, 'robots.txt'), robots, 'utf8');

if (siteUrl) {
  const urls = [siteUrl + '/', ...updatedManifest.map(game => `${siteUrl}${game.url}`)];
  const sitemap = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(url => `  <url><loc>${escapeHtml(url)}</loc><lastmod>${date}</lastmod></url>`).join('\n')}\n</urlset>\n`;
  await fs.writeFile(path.join(PUBLIC_DIR, 'sitemap.xml'), sitemap, 'utf8');
}

console.log(`4/4 Created: ${plan.title}`);
console.log(`Game folder: public/games/${slug}/`);
console.log(`Game URL: ${gameUrl}`);
