import fs from 'node:fs/promises';
import path from 'node:path';
import { AUTO_DIR, GAMES_DIR, PUBLIC_DIR, choice, ensureFolders, escapeHtml, isoDate, readJson, seeded, slugify, timeId, validateGameHtml, writeJson } from './common.mjs';

const WORLDS = ['ice cream planet','robot carnival','moon desert','jungle subway','pirate classroom','laser aquarium','candy volcano','cloud factory','haunted arcade','tiny city','crystal cave','space bakery'];
const PALETTES = [
  ['#61f4ff','#ffe36e','#0b1020'], ['#ff72c6','#6ef7b2','#180b22'], ['#a78bfa','#facc15','#08111f'], ['#7cffcb','#ff7b7b','#07131d'], ['#8be9fd','#ffb86c','#101022']
];

const ENGINES = [
  { id:'snake-board', genre:'Snake', name:'Grid Snake Lab', maker: makeSnake },
  { id:'typing-rain', genre:'Typing', name:'Keyboard Rain Rescue', maker: makeTypingRain },
  { id:'memory-cards', genre:'Memory', name:'Flip Card Monster Match', maker: makeMemoryCards },
  { id:'whack-lights', genre:'Reaction', name:'Whack The Light Bugs', maker: makeWhack },
  { id:'flappy-gates', genre:'Flying', name:'One Button Cloud Flight', maker: makeFlappy },
  { id:'lane-racer', genre:'Racing', name:'Neon Lane Racer', maker: makeRacer },
  { id:'brick-blaster', genre:'Breakout', name:'Brick Blaster Arena', maker: makeBreakout },
  { id:'maze-keys', genre:'Maze', name:'Maze Keys Escape', maker: makeMaze },
  { id:'paddle-duel', genre:'Pong', name:'Paddle Duel Galaxy', maker: makePong },
  { id:'rhythm-tap', genre:'Rhythm', name:'Beat Tap Studio', maker: makeRhythm },
  { id:'mining-grid', genre:'Mining', name:'Treasure Mine Clicker', maker: makeMining },
  { id:'tower-stack', genre:'Timing', name:'Stack Tower Builder', maker: makeStacker },
  { id:'golf-shot', genre:'Aim', name:'Mini Golf Shot', maker: makeGolf },
  { id:'color-brain', genre:'Puzzle', name:'Color Brain Switch', maker: makeColorBrain },
  { id:'space-shooter', genre:'Shooter', name:'Tiny Space Defender', maker: makeSpaceShooter },
  { id:'platform-coins', genre:'Platformer', name:'Coin Cave Platformer', maker: makePlatformer },
  { id:'basket-arc', genre:'Sports', name:'Basket Arc Challenge', maker: makeBasket },
  { id:'simon-orbs', genre:'Pattern', name:'Simon Orb Memory', maker: makeSimon },
  { id:'fishing-timing', genre:'Fishing', name:'Fishing Timing Dock', maker: makeFishing },
  { id:'avoid-arena', genre:'Survival', name:'Avoid Arena Swarm', maker: makeAvoid }
];

function chooseEngine(manifest) {
  const recentCount = Math.min(ENGINES.length - 1, 40);
  const recent = new Set(manifest.slice(0, recentCount).map(g => g.engineId).filter(Boolean));
  const candidates = ENGINES.filter(e => !recent.has(e.id));
  const pool = candidates.length ? candidates : ENGINES;
  return pool[seeded(`${timeId()}-${manifest.length}`, 0, pool.length - 1)];
}

function cfg(engine, manifest) {
  const seed = `${timeId()}-${engine.id}-${manifest.length}`;
  const world = choice(WORLDS, seed);
  const palette = choice(PALETTES, seed + '-p');
  const number = seeded(seed, 10, 99);
  const title = `${engine.name} ${number}`;
  return { title, world, genre: engine.genre, engineId: engine.id, a: palette[0], b: palette[1], bg: palette[2], seed };
}

function baseMeta(c) {
  return `<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><title>${escapeHtml(c.title)}</title><meta name="description" content="${escapeHtml(c.genre + ' game in ' + c.world)}">`;
}

function makeSnake(c){return `<!doctype html><html><head>${baseMeta(c)}<style>body{margin:0;background:${c.bg};color:white;font-family:monospace;display:grid;place-items:center;min-height:100vh}.box{width:min(92vw,680px);text-align:center}canvas{background:#07121f;border:12px solid ${c.a};box-shadow:0 0 40px ${c.a};width:100%;aspect-ratio:1;border-radius:24px}.bar{display:flex;justify-content:space-between;font-size:24px;margin:12px}.pad button{font-size:30px;margin:6px;border:0;border-radius:16px;padding:12px 22px;background:${c.b};font-weight:900}</style></head><body><div class="box"><h1>${escapeHtml(c.title)}</h1><p>Different game type: Snake. World: ${escapeHtml(c.world)}.</p><div class="bar"><b>Score <span id=s>0</span></b><b id=m>eat 12 orbs</b></div><canvas id=g width=600 height=600></canvas><div class=pad><button id=l>◀</button><button id=u>▲</button><button id=r>▶</button><button id=d>▼</button></div></div><script>const C=document.getElementById('g'),x=C.getContext('2d'),s=document.getElementById('s'),N=20,Z=30;let snake,food,dir,next,score,over=false;function reset(){snake=[[9,9],[8,9],[7,9]];food=[15,12];dir=[1,0];next=[1,0];score=0;over=false;s.textContent=0}function place(){food=[Math.floor(Math.random()*N),Math.floor(Math.random()*N)]}function draw(){x.fillStyle='#050b12';x.fillRect(0,0,600,600);x.strokeStyle='rgba(255,255,255,.08)';for(let i=0;i<=N;i++){x.beginPath();x.moveTo(i*Z,0);x.lineTo(i*Z,600);x.moveTo(0,i*Z);x.lineTo(600,i*Z);x.stroke()}x.fillStyle='${c.b}';x.fillRect(food[0]*Z+5,food[1]*Z+5,20,20);snake.forEach((p,i)=>{x.fillStyle=i?'${c.a}':'#fff';x.fillRect(p[0]*Z+3,p[1]*Z+3,24,24)});if(over){x.fillStyle='#fff';x.font='46px monospace';x.fillText('Game Over',175,300)}}function step(){if(over)return;dir=next;let h=[snake[0][0]+dir[0],snake[0][1]+dir[1]];if(h[0]<0||h[1]<0||h[0]>=N||h[1]>=N||snake.some(p=>p[0]===h[0]&&p[1]===h[1]))over=true;snake.unshift(h);if(h[0]===food[0]&&h[1]===food[1]){score++;s.textContent=score;place();if(score>=12)document.getElementById('m').textContent='YOU WIN'}else snake.pop();draw()}function turn(a,b){if(dir[0]!==-a||dir[1]!==-b)next=[a,b]}onkeydown=e=>{if(e.key==='ArrowLeft')turn(-1,0);if(e.key==='ArrowRight')turn(1,0);if(e.key==='ArrowUp')turn(0,-1);if(e.key==='ArrowDown')turn(0,1)};l.onclick=()=>turn(-1,0);r.onclick=()=>turn(1,0);u.onclick=()=>turn(0,-1);d.onclick=()=>turn(0,1);reset();draw();setInterval(step,130)</script></body></html>`}

function makeTypingRain(c){return `<!doctype html><html><head>${baseMeta(c)}<style>body{margin:0;background:linear-gradient(#061021,#0b2836);color:white;font-family:Arial;overflow:hidden}.hud{position:fixed;inset:18px 18px auto;display:flex;justify-content:space-between;font-size:24px;font-weight:900}.letter{position:absolute;font-size:46px;font-weight:1000;color:${c.a};text-shadow:0 0 18px ${c.a}}.hero{position:fixed;bottom:30px;left:50%;transform:translateX(-50%);font-size:80px}.start{position:fixed;inset:0;display:grid;place-items:center;background:#000a}.card{background:#111d2d;border:2px solid ${c.b};border-radius:30px;padding:30px;text-align:center;max-width:600px}button{background:${c.b};border:0;border-radius:14px;padding:15px 25px;font-size:22px;font-weight:900}</style></head><body><div class=hud><span>${escapeHtml(c.title)}</span><span>Score <b id=s>0</b> · Lives <b id=l>5</b></span></div><div class=hero>⌨️</div><div class=start id=start><div class=card><h1>Keyboard Rain Rescue</h1><p>Type the falling letters before they hit the keyboard. This is not an arcade template.</p><button onclick="go()">Start</button></div></div><script>let score=0,lives=5,items=[],run=false;const letters='ABCDEFGHJKLMNPQRSTUVWXYZ';function go(){start.style.display='none';run=true;setInterval(spawn,650);requestAnimationFrame(loop)}function spawn(){if(!run)return;let d=document.createElement('div');d.className='letter';d.textContent=letters[Math.floor(Math.random()*letters.length)];d.style.left=Math.random()*90+'vw';d.y=-50;document.body.appendChild(d);items.push(d)}function loop(){if(!run)return;for(const d of [...items]){d.y+=2+score*.015;d.style.top=d.y+'px';if(d.y>innerHeight-110){d.remove();items=items.filter(x=>x!==d);lives--;l.textContent=lives;if(lives<=0){run=false;alert('Game over. Score '+score)}}}requestAnimationFrame(loop)}onkeydown=e=>{let k=e.key.toUpperCase();let d=items.find(x=>x.textContent===k);if(d){d.remove();items=items.filter(x=>x!==d);score+=10;s.textContent=score}}</script></body></html>`}

function makeMemoryCards(c){return `<!doctype html><html><head>${baseMeta(c)}<style>body{margin:0;min-height:100vh;background:radial-gradient(circle,${c.a},${c.bg} 55%);font-family:Verdana;color:white;display:grid;place-items:center}.panel{width:min(900px,94vw);background:#0008;border-radius:28px;padding:22px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.card{height:110px;border-radius:18px;background:#111;display:grid;place-items:center;font-size:44px;cursor:pointer;box-shadow:inset 0 0 0 3px #fff2}.open{background:${c.b};color:#111}h1{margin-top:0}.score{font-size:24px;font-weight:900}</style></head><body><main class=panel><h1>${escapeHtml(c.title)}</h1><p>Flip cards and find pairs. World: ${escapeHtml(c.world)}</p><div class=score>Moves <span id=m>0</span> · Pairs <span id=p>0</span>/8</div><div class=grid id=grid></div></main><script>const icons='🐸 🚀 🍕 👾 🐙 🧊 🎧 🏆'.split(' ');let vals=[...icons,...icons].sort(()=>Math.random()-.5),first=null,moves=0,pairs=0;vals.forEach((v,i)=>{let e=document.createElement('button');e.className='card';e.dataset.v=v;e.textContent='?';e.onclick=()=>flip(e);grid.appendChild(e)});function flip(e){if(e.classList.contains('open')||e.done)return;e.classList.add('open');e.textContent=e.dataset.v;if(!first){first=e;return}moves++;m.textContent=moves;if(first.dataset.v===e.dataset.v){first.done=e.done=true;pairs++;p.textContent=pairs;if(pairs===8)setTimeout(()=>alert('You win in '+moves+' moves'),200)}else{let a=first;setTimeout(()=>{a.classList.remove('open');e.classList.remove('open');a.textContent=e.textContent='?'},650)}first=null}</script></body></html>`}

function makeWhack(c){return `<!doctype html><html><head>${baseMeta(c)}<style>body{margin:0;background:#17091d;color:#fff;font-family:Arial;text-align:center}.holes{display:grid;grid-template-columns:repeat(3,minmax(90px,160px));gap:18px;justify-content:center;margin:20px}.hole{height:130px;border-radius:50%;background:#050505;border:8px solid ${c.a};display:grid;place-items:center;font-size:70px;cursor:pointer}.on{background:${c.b};box-shadow:0 0 30px ${c.b}}h1{font-size:48px}.hud{font-size:26px;font-weight:900}</style></head><body><h1>${escapeHtml(c.title)}</h1><p>Reaction game: hit the bug when it appears.</p><div class=hud>Score <span id=s>0</span> · Time <span id=t>30</span></div><div class=holes id=h></div><script>let score=0,time=30,active=-1;for(let i=0;i<9;i++){let b=document.createElement('button');b.className='hole';b.textContent='';b.onclick=()=>{if(i===active){score++;s.textContent=score;hide()}else score=Math.max(0,score-1);};h.appendChild(b)}let holes=[...document.querySelectorAll('.hole')];function hide(){holes.forEach(x=>{x.classList.remove('on');x.textContent=''})}function show(){hide();active=Math.floor(Math.random()*9);holes[active].classList.add('on');holes[active].textContent='🪲'}setInterval(show,700);let timer=setInterval(()=>{time--;t.textContent=time;if(time<=0){clearInterval(timer);alert('Finished: '+score)}},1000)</script></body></html>`}

function makeFlappy(c){return `<!doctype html><html><head>${baseMeta(c)}<style>body{margin:0;background:#84d9ff;font-family:Arial;overflow:hidden}canvas{display:block;width:100vw;height:100vh}.tip{position:fixed;top:12px;left:12px;background:white;border-radius:14px;padding:10px 14px;font-weight:900}</style></head><body><div class=tip>${escapeHtml(c.title)} · click/space to flap · <span id=s>0</span></div><canvas id=cv></canvas><script>const cva=cv,ctx=cva.getContext('2d');let W,H,bird,pipes,score,vy,run=true;function R(){W=cva.width=innerWidth;H=cva.height=innerHeight}onresize=R;R();function reset(){bird={x:W*.25,y:H/2};vy=0;pipes=[];score=0}function flap(){vy=-8}onclick=flap;onkeydown=e=>{if(e.code==='Space')flap()};function loop(){ctx.fillStyle='#79d8ff';ctx.fillRect(0,0,W,H);vy+=.45;bird.y+=vy;if(!pipes.length||pipes[pipes.length-1].x<W-280){let gap=170,top=80+Math.random()*(H-320);pipes.push({x:W,top,gap,pass:false})}pipes.forEach(p=>{p.x-=3;ctx.fillStyle='${c.a}';ctx.fillRect(p.x,0,70,p.top);ctx.fillRect(p.x,p.top+p.gap,70,H);if(!p.pass&&p.x<bird.x){p.pass=true;score++;s.textContent=score}if(bird.x+18>p.x&&bird.x-18<p.x+70&&(bird.y-18<p.top||bird.y+18>p.top+p.gap))reset()});pipes=pipes.filter(p=>p.x>-90);ctx.fillStyle='${c.b}';ctx.beginPath();ctx.arc(bird.x,bird.y,20,0,7);ctx.fill();if(bird.y<0||bird.y>H)reset();requestAnimationFrame(loop)}reset();loop()</script></body></html>`}

function makeRacer(c){return `<!doctype html><html><head>${baseMeta(c)}<style>body{margin:0;background:#050508;color:#fff;font-family:Arial;overflow:hidden}canvas{width:100vw;height:100vh;display:block}.hud{position:fixed;top:20px;left:50%;transform:translateX(-50%);background:#0009;padding:12px 22px;border-radius:999px;font-size:22px;font-weight:900}</style></head><body><div class=hud>${escapeHtml(c.title)} · Score <span id=s>0</span></div><canvas id=cv></canvas><script>const x=cv.getContext('2d');let W,H,lane=1,cars=[],score=0;function size(){W=cv.width=innerWidth;H=cv.height=innerHeight}onresize=size;size();function add(){cars.push({lane:Math.floor(Math.random()*3),y:-120})}setInterval(add,650);onkeydown=e=>{if(e.key==='ArrowLeft')lane=Math.max(0,lane-1);if(e.key==='ArrowRight')lane=Math.min(2,lane+1)};onclick=e=>{lane=e.clientX<W/2?Math.max(0,lane-1):Math.min(2,lane+1)};function loop(){x.fillStyle='#06060d';x.fillRect(0,0,W,H);let lw=W/3;for(let i=1;i<3;i++){x.strokeStyle='${c.a}';x.setLineDash([25,25]);x.lineWidth=4;x.beginPath();x.moveTo(i*lw,0);x.lineTo(i*lw,H);x.stroke()}cars.forEach(o=>{o.y+=5+score*.02;x.fillStyle='${c.b}';x.fillRect(o.lane*lw+lw*.25,o.y,lw*.5,90);if(o.y>H){o.dead=true;score++;s.textContent=score}if(o.lane===lane&&o.y>H-170&&o.y<H-40){score=0;s.textContent=0;cars=[]}});cars=cars.filter(o=>!o.dead);x.fillStyle='#fff';x.fillRect(lane*lw+lw*.22,H-135,lw*.56,100);requestAnimationFrame(loop)}loop()</script></body></html>`}

function makeBreakout(c){return `<!doctype html><html><head>${baseMeta(c)}<style>body{margin:0;background:#111;color:white;font-family:Arial}canvas{display:block;margin:auto;max-width:100vw;height:100vh;background:linear-gradient(#20113b,#070712)}</style></head><body><canvas id=cv width=900 height=700></canvas><script>const x=cv.getContext('2d');let p={x:380,y:650,w:140,h:18},b={x:450,y:500,vx:4,vy:-5,r:10},score=0,br=[];for(let y=0;y<5;y++)for(let i=0;i<10;i++)br.push({x:35+i*82,y:55+y*38,w:70,h:25});onmousemove=e=>p.x=e.clientX/cv.getBoundingClientRect().width*900-p.w/2;onkeydown=e=>{if(e.key==='ArrowLeft')p.x-=40;if(e.key==='ArrowRight')p.x+=40};function loop(){x.clearRect(0,0,900,700);x.fillStyle='${c.a}';br.forEach(r=>x.fillRect(r.x,r.y,r.w,r.h));x.fillStyle='${c.b}';x.fillRect(p.x,p.y,p.w,p.h);x.beginPath();x.arc(b.x,b.y,b.r,0,7);x.fillStyle='#fff';x.fill();b.x+=b.vx;b.y+=b.vy;if(b.x<10||b.x>890)b.vx*=-1;if(b.y<10)b.vy*=-1;if(b.y>700){b.x=450;b.y=500;score=0}if(b.x>p.x&&b.x<p.x+p.w&&b.y+b.r>p.y)b.vy=-Math.abs(b.vy);br=br.filter(r=>{let hit=b.x>r.x&&b.x<r.x+r.w&&b.y>r.y&&b.y<r.y+r.h;if(hit){b.vy*=-1;score+=10}return !hit});x.font='26px Arial';x.fillText('${escapeHtml(c.title)} Score '+score,25,35);requestAnimationFrame(loop)}loop()</script></body></html>`}

function makeMaze(c){return `<!doctype html><html><head>${baseMeta(c)}<style>body{margin:0;background:${c.bg};color:white;font-family:Arial;display:grid;place-items:center;height:100vh}.m{font-size:28px}.grid{display:grid;grid-template-columns:repeat(12,42px);gap:4px}.cell{width:42px;height:42px;background:#112}.wall{background:${c.a}}.p{background:#fff}.k{background:${c.b}}.e{background:#5f5}</style></head><body><div><h1>${escapeHtml(c.title)}</h1><p class=m>Keys <span id=ks>0</span>/3</p><div class=grid id=g></div></div><script>let map=['############','#P....#....#','#.##..#.##.#','#..#..#..#K#','##.#.##..#.#','#..#...#...#','#.####.#.#.#','#....K.#.#.#','#.##.###.#.#','#......#...#','#K####...#E#','############'];let px=1,py=1,keys=0;function draw(){g.innerHTML='';map.forEach((row,y)=>[...row].forEach((ch,x)=>{let d=document.createElement('div');d.className='cell '+(ch==='#'?'wall':ch==='K'?'k':ch==='E'?'e':'');if(x===px&&y===py)d.className='cell p';g.appendChild(d)}));ks.textContent=keys}function move(dx,dy){let nx=px+dx,ny=py+dy,ch=map[ny][nx];if(ch==='#')return;px=nx;py=ny;if(ch==='K'){keys++;map[ny]=map[ny].slice(0,nx)+'.'+map[ny].slice(nx+1)}if(ch==='E'&&keys>=3)alert('Escaped!');draw()}onkeydown=e=>{if(e.key==='ArrowLeft')move(-1,0);if(e.key==='ArrowRight')move(1,0);if(e.key==='ArrowUp')move(0,-1);if(e.key==='ArrowDown')move(0,1)};draw()</script></body></html>`}

function makePong(c){return `<!doctype html><html><head>${baseMeta(c)}<style>body{margin:0;background:#000;color:white;font-family:Arial;overflow:hidden}canvas{display:block;width:100vw;height:100vh}.label{position:fixed;top:12px;left:12px;font-size:22px;font-weight:900}</style></head><body><div class=label>${escapeHtml(c.title)} <span id=s>0</span></div><canvas id=cv></canvas><script>const x=cv.getContext('2d');let W,H,p=0,ai=0,b,score=0;function size(){W=cv.width=innerWidth;H=cv.height=innerHeight;p=H/2;ai=H/2;b={x:W/2,y:H/2,vx:5,vy:3}}onresize=size;size();onmousemove=e=>p=e.clientY;onkeydown=e=>{if(e.key==='ArrowUp')p-=50;if(e.key==='ArrowDown')p+=50};function loop(){x.fillStyle='#000';x.fillRect(0,0,W,H);b.x+=b.vx;b.y+=b.vy;ai+=(b.y-ai)*.06;if(b.y<0||b.y>H)b.vy*=-1;if(b.x<30&&Math.abs(b.y-p)<70){b.vx=Math.abs(b.vx)+.2;score++;s.textContent=score}if(b.x>W-30&&Math.abs(b.y-ai)<70)b.vx=-Math.abs(b.vx)-.2;if(b.x<0||b.x>W)size();x.fillStyle='${c.a}';x.fillRect(18,p-70,18,140);x.fillStyle='${c.b}';x.fillRect(W-36,ai-70,18,140);x.fillStyle='#fff';x.beginPath();x.arc(b.x,b.y,12,0,7);x.fill();requestAnimationFrame(loop)}loop()</script></body></html>`}

function makeRhythm(c){return `<!doctype html><html><head>${baseMeta(c)}<style>body{margin:0;background:#12051d;color:white;font-family:Arial;text-align:center}.lane{height:70vh;display:flex;align-items:end;justify-content:center;gap:20px}.beat{width:90px;height:90px;border-radius:50%;background:${c.a};display:grid;place-items:center;font-size:30px;font-weight:900;transform:translateY(-70vh)}.target{position:fixed;bottom:80px;left:0;right:0;font-size:70px}button{font-size:26px;padding:15px 30px;border-radius:18px;border:0;background:${c.b};font-weight:900}</style></head><body><h1>${escapeHtml(c.title)}</h1><h2>Score <span id=s>0</span></h2><div class=lane id=lane></div><div class=target>🥁</div><button onclick="tap()">TAP / Space</button><script>let beats=[],score=0;function spawn(){let b=document.createElement('div');b.className='beat';b.textContent='●';b.y=-innerHeight*.7;lane.appendChild(b);beats.push(b)}setInterval(spawn,900);function tap(){let best=beats[0];if(!best)return;let pos=best.getBoundingClientRect().bottom;let target=innerHeight-80;if(Math.abs(pos-target)<80){score+=10;best.remove();beats.shift()}else score=Math.max(0,score-3);s.textContent=score}onkeydown=e=>{if(e.code==='Space')tap()};function loop(){beats.forEach(b=>{b.y+=5;b.style.transform='translateY('+b.y+'px)'});beats=beats.filter(b=>{if(b.y>innerHeight){b.remove();return false}return true});requestAnimationFrame(loop)}loop()</script></body></html>`}

function makeMining(c){return `<!doctype html><html><head>${baseMeta(c)}<style>body{margin:0;background:#2b1607;color:#ffe;font-family:Georgia;text-align:center}.grid{display:grid;grid-template-columns:repeat(8,70px);gap:8px;justify-content:center}.rock{height:70px;border-radius:12px;border:0;background:#5a3924;font-size:30px}.gold{background:${c.b}}h1{font-size:42px}</style></head><body><h1>${escapeHtml(c.title)}</h1><h2>Gold <span id=s>0</span>/12</h2><div class=grid id=g></div><script>let score=0;for(let i=0;i<64;i++){let b=document.createElement('button');b.className='rock';b.textContent='🪨';b.gold=Math.random()<.22;b.onclick=()=>{if(b.done)return;b.done=true;if(b.gold){b.className='rock gold';b.textContent='💰';score++;s.textContent=score;if(score>=12)alert('Mine cleared!')}else{b.textContent='🕳️';b.style.opacity=.55}};g.appendChild(b)}</script></body></html>`}

function makeStacker(c){return `<!doctype html><html><head>${baseMeta(c)}<style>body{margin:0;background:#07101c;color:white;font-family:Arial;overflow:hidden}canvas{width:100vw;height:100vh;display:block}.h{position:fixed;top:20px;left:20px;font-size:28px;font-weight:900}</style></head><body><div class=h>${escapeHtml(c.title)} Height <span id=s>0</span></div><canvas id=cv></canvas><script>const x=cv.getContext('2d');let W,H,blocks=[],move,dir=1,score=0;function size(){W=cv.width=innerWidth;H=cv.height=innerHeight;blocks=[{x:W/2-120,y:H-60,w:240,h:30}];newBlock()}onresize=size;size();function newBlock(){let last=blocks[blocks.length-1];move={x:0,y:last.y-32,w:last.w,h:30}}function drop(){let last=blocks[blocks.length-1];let overlap=Math.max(0,Math.min(move.x+move.w,last.x+last.w)-Math.max(move.x,last.x));if(overlap<20){alert('Tower '+score);size();score=0;return}move.w=overlap;move.x=Math.max(move.x,last.x);blocks.push(move);score++;s.textContent=score;newBlock()}onclick=drop;onkeydown=e=>{if(e.code==='Space')drop()};function loop(){x.fillStyle='${c.bg}';x.fillRect(0,0,W,H);move.x+=dir*5;if(move.x<0||move.x+move.w>W)dir*=-1;let camera=Math.max(0,blocks[blocks.length-1].y-H*.5);[...blocks,move].forEach((b,i)=>{x.fillStyle=i%2?'${c.a}':'${c.b}';x.fillRect(b.x,b.y+camera,b.w,b.h)});requestAnimationFrame(loop)}loop()</script></body></html>`}

function makeGolf(c){return `<!doctype html><html><head>${baseMeta(c)}<style>body{margin:0;background:#184d2b;color:white;font-family:Arial;overflow:hidden}canvas{width:100vw;height:100vh;display:block}.ui{position:fixed;top:18px;left:18px;background:#0008;padding:14px;border-radius:16px;font-weight:900}</style></head><body><div class=ui>${escapeHtml(c.title)} · drag/click to shoot · Shots <span id=s>0</span></div><canvas id=cv></canvas><script>const x=cv.getContext('2d');let W,H,ball,hole,shots=0;function size(){W=cv.width=innerWidth;H=cv.height=innerHeight;ball={x:80,y:H-90,vx:0,vy:0};hole={x:W-90,y:90,r:25}}onresize=size;size();onclick=e=>{ball.vx=(e.clientX-ball.x)/18;ball.vy=(e.clientY-ball.y)/18;shots++;s.textContent=shots};function loop(){x.fillStyle='#1b7b43';x.fillRect(0,0,W,H);x.fillStyle='#111';x.beginPath();x.arc(hole.x,hole.y,hole.r,0,7);x.fill();ball.x+=ball.vx;ball.y+=ball.vy;ball.vx*=.985;ball.vy*=.985;if(ball.x<15||ball.x>W-15)ball.vx*=-.8;if(ball.y<15||ball.y>H-15)ball.vy*=-.8;x.fillStyle='#fff';x.beginPath();x.arc(ball.x,ball.y,14,0,7);x.fill();if(Math.hypot(ball.x-hole.x,ball.y-hole.y)<hole.r){alert('Hole in '+shots);size();shots=0;s.textContent=0}requestAnimationFrame(loop)}loop()</script></body></html>`}

function makeColorBrain(c){return `<!doctype html><html><head>${baseMeta(c)}<style>body{margin:0;background:${c.bg};color:white;font-family:Arial;display:grid;place-items:center;min-height:100vh}.card{max-width:780px;text-align:center;background:#ffffff12;padding:34px;border-radius:30px}.word{font-size:80px;font-weight:1000}.btns{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}button{font-size:24px;border:0;border-radius:16px;padding:20px;font-weight:900}</style></head><body><div class=card><h1>${escapeHtml(c.title)}</h1><p>Click the COLOR of the word, not the text.</p><div class=word id=w>RED</div><h2>Score <span id=s>0</span></h2><div class=btns id=b></div></div><script>const colors={RED:'#ff4d6d',BLUE:'#4dabff',GREEN:'#69db7c',YELLOW:'#ffd43b'};let score=0,answer='RED';Object.keys(colors).forEach(k=>{let bt=document.createElement('button');bt.textContent=k;bt.style.background=colors[k];bt.onclick=()=>{if(k===answer)score++;else score=Math.max(0,score-1);s.textContent=score;next()};b.appendChild(bt)});function next(){let names=Object.keys(colors);w.textContent=names[Math.floor(Math.random()*4)];answer=names[Math.floor(Math.random()*4)];w.style.color=colors[answer]}next()</script></body></html>`}

function makeSpaceShooter(c){return `<!doctype html><html><head>${baseMeta(c)}<style>body{margin:0;background:#000;color:white;overflow:hidden;font-family:Arial}canvas{width:100vw;height:100vh;display:block}.hud{position:fixed;top:14px;left:14px;font-size:23px;font-weight:900}</style></head><body><div class=hud>${escapeHtml(c.title)} Score <span id=s>0</span></div><canvas id=cv></canvas><script>const x=cv.getContext('2d');let W,H,ship,bul=[],en=[],score=0;function size(){W=cv.width=innerWidth;H=cv.height=innerHeight;ship={x:W/2,y:H-70}}onresize=size;size();onmousemove=e=>ship.x=e.clientX;onclick=()=>bul.push({x:ship.x,y:ship.y});onkeydown=e=>{if(e.key==='ArrowLeft')ship.x-=50;if(e.key==='ArrowRight')ship.x+=50;if(e.code==='Space')bul.push({x:ship.x,y:ship.y})};setInterval(()=>en.push({x:Math.random()*W,y:-30}),650);function loop(){x.fillStyle='#000';x.fillRect(0,0,W,H);x.fillStyle='${c.a}';x.beginPath();x.moveTo(ship.x,ship.y-24);x.lineTo(ship.x-22,ship.y+24);x.lineTo(ship.x+22,ship.y+24);x.fill();bul.forEach(b=>{b.y-=9;x.fillStyle='${c.b}';x.fillRect(b.x-3,b.y,6,20)});en.forEach(e=>{e.y+=3;x.fillStyle='#ff5d73';x.beginPath();x.arc(e.x,e.y,18,0,7);x.fill();bul.forEach(b=>{if(Math.hypot(b.x-e.x,b.y-e.y)<24){e.dead=b.dead=true;score+=10;s.textContent=score}});if(Math.hypot(ship.x-e.x,ship.y-e.y)<35){score=0;s.textContent=0;en=[]}});bul=bul.filter(b=>!b.dead&&b.y>-30);en=en.filter(e=>!e.dead&&e.y<H+50);requestAnimationFrame(loop)}loop()</script></body></html>`}

function makePlatformer(c){return `<!doctype html><html><head>${baseMeta(c)}<style>body{margin:0;background:#0a1220;color:white;font-family:Arial}canvas{display:block;width:100vw;height:100vh}.hud{position:fixed;top:18px;left:18px;font-size:24px;font-weight:900}</style></head><body><div class=hud>${escapeHtml(c.title)} Coins <span id=s>0</span></div><canvas id=cv></canvas><script>const x=cv.getContext('2d');let W,H,p,vy=0,coins,score=0;function size(){W=cv.width=innerWidth;H=cv.height=innerHeight;p={x:60,y:H-90,w:32,h:48};coins=[200,380,560,740,920].map((xx,i)=>({x:xx,y:H-150-i%2*80}))}onresize=size;size();let key={};onkeydown=e=>key[e.key]=true;onkeyup=e=>key[e.key]=false;function loop(){x.fillStyle='${c.bg}';x.fillRect(0,0,W,H);let ground=H-40;if(key.ArrowLeft)p.x-=5;if(key.ArrowRight)p.x+=5;if((key.ArrowUp||key[' '])&&p.y+p.h>=ground)vy=-13;vy+=.55;p.y+=vy;if(p.y+p.h>ground){p.y=ground-p.h;vy=0}x.fillStyle='${c.a}';x.fillRect(0,ground,W,40);x.fillStyle='white';x.fillRect(p.x,p.y,p.w,p.h);coins.forEach(cn=>{x.fillStyle='${c.b}';x.beginPath();x.arc(cn.x,cn.y,14,0,7);x.fill();if(Math.abs(p.x-cn.x)<35&&Math.abs(p.y-cn.y)<55){cn.got=true;score++;s.textContent=score}});coins=coins.filter(c=>!c.got);if(coins.length===0){alert('All coins!');size();score=0;s.textContent=0}requestAnimationFrame(loop)}loop()</script></body></html>`}

function makeBasket(c){return `<!doctype html><html><head>${baseMeta(c)}<style>body{margin:0;background:#ffe3bd;font-family:Arial;overflow:hidden}canvas{width:100vw;height:100vh;display:block}.hud{position:fixed;top:12px;left:12px;background:white;padding:12px;border-radius:14px;font-weight:900}</style></head><body><div class=hud>${escapeHtml(c.title)} Score <span id=s>0</span></div><canvas id=cv></canvas><script>const x=cv.getContext('2d');let W,H,ball={x:90,y:0,vx:0,vy:0},score=0;function size(){W=cv.width=innerWidth;H=cv.height=innerHeight;ball={x:90,y:H-90,vx:0,vy:0}}onresize=size;size();onclick=e=>{ball.vx=(e.clientX-ball.x)/22;ball.vy=(e.clientY-ball.y)/22};function loop(){x.fillStyle='#ffd6a3';x.fillRect(0,0,W,H);let rim={x:W-120,y:160};x.strokeStyle='#c33';x.lineWidth=8;x.beginPath();x.arc(rim.x,rim.y,38,0,Math.PI);x.stroke();ball.vy+=.35;ball.x+=ball.vx;ball.y+=ball.vy;if(ball.y>H-20){ball.y=H-20;ball.vy*=-.55;ball.vx*=.86}x.fillStyle='#f97316';x.beginPath();x.arc(ball.x,ball.y,22,0,7);x.fill();if(Math.abs(ball.x-rim.x)<34&&Math.abs(ball.y-rim.y)<20&&ball.vy>0){score++;s.textContent=score;size()}requestAnimationFrame(loop)}loop()</script></body></html>`}

function makeSimon(c){return `<!doctype html><html><head>${baseMeta(c)}<style>body{margin:0;background:#090e22;color:white;font-family:Arial;display:grid;place-items:center;height:100vh}.box{text-align:center}.orbs{display:grid;grid-template-columns:repeat(2,160px);gap:18px}.orb{height:160px;border-radius:50%;border:0;font-size:40px;filter:brightness(.65)}.lit{filter:brightness(1.8);box-shadow:0 0 45px white}button{cursor:pointer}</style></head><body><div class=box><h1>${escapeHtml(c.title)}</h1><h2>Level <span id=l>1</span></h2><div class=orbs id=o></div><p>Repeat the glowing pattern.</p></div><script>let colors=['${c.a}','${c.b}','#ff5d73','#b197fc'],seq=[],pos=0,playing=false;colors.forEach((col,i)=>{let b=document.createElement('button');b.className='orb';b.style.background=col;b.onclick=()=>press(i);o.appendChild(b)});let bs=[...document.querySelectorAll('.orb')];function flash(i){bs[i].classList.add('lit');setTimeout(()=>bs[i].classList.remove('lit'),350)}function next(){seq.push(Math.floor(Math.random()*4));pos=0;l.textContent=seq.length;playing=true;seq.forEach((n,i)=>setTimeout(()=>flash(n),600+i*520));setTimeout(()=>playing=false,700+seq.length*520)}function press(i){if(playing)return;flash(i);if(i!==seq[pos]){alert('Wrong! reached '+seq.length);seq=[];next();return}pos++;if(pos===seq.length)setTimeout(next,600)}next()</script></body></html>`}

function makeFishing(c){return `<!doctype html><html><head>${baseMeta(c)}<style>body{margin:0;background:linear-gradient(#8ad7ff 0 45%,#086788 45%);font-family:Arial;text-align:center;color:#052}.dock{font-size:120px;margin-top:80px}.meter{width:min(80vw,700px);height:50px;background:white;border-radius:999px;margin:30px auto;position:relative}.zone{position:absolute;height:100%;width:90px;background:${c.b};border-radius:999px;left:50%}.hook{position:absolute;top:-10px;width:16px;height:70px;background:${c.a};border-radius:9px}button{font-size:28px;border:0;border-radius:18px;padding:16px 32px;background:${c.b};font-weight:900}</style></head><body><h1>${escapeHtml(c.title)}</h1><h2>Fish <span id=s>0</span></h2><div class=dock>🎣</div><div class=meter id=m><div class=zone></div><div class=hook id=h></div></div><button onclick="catchFish()">Catch!</button><script>let x=0,v=4,score=0;function loop(){x+=v;if(x<0||x>m.clientWidth-16)v*=-1;h.style.left=x+'px';requestAnimationFrame(loop)}function catchFish(){let z=m.clientWidth/2;if(Math.abs(x-z)<65){score++;s.textContent=score}else score=Math.max(0,score-1)}loop()</script></body></html>`}

function makeAvoid(c){return `<!doctype html><html><head>${baseMeta(c)}<style>body{margin:0;background:${c.bg};color:white;font-family:Arial;overflow:hidden}canvas{width:100vw;height:100vh;display:block}.hud{position:fixed;top:15px;right:15px;font-size:24px;font-weight:900}</style></head><body><div class=hud>${escapeHtml(c.title)} Time <span id=s>0</span></div><canvas id=cv></canvas><script>const x=cv.getContext('2d');let W,H,p,en=[],score=0;function size(){W=cv.width=innerWidth;H=cv.height=innerHeight;p={x:W/2,y:H/2}}onresize=size;size();onmousemove=e=>{p.x=e.clientX;p.y=e.clientY};setInterval(()=>en.push({x:Math.random()*W,y:Math.random()*H,vx:(Math.random()-.5)*5,vy:(Math.random()-.5)*5}),800);function loop(){score++;s.textContent=Math.floor(score/60);x.fillStyle='${c.bg}';x.fillRect(0,0,W,H);x.fillStyle='${c.a}';x.beginPath();x.arc(p.x,p.y,18,0,7);x.fill();en.forEach(e=>{e.x+=e.vx;e.y+=e.vy;if(e.x<0||e.x>W)e.vx*=-1;if(e.y<0||e.y>H)e.vy*=-1;x.fillStyle='${c.b}';x.beginPath();x.arc(e.x,e.y,24,0,7);x.fill();if(Math.hypot(p.x-e.x,p.y-e.y)<42){alert('Survived '+Math.floor(score/60)+' seconds');en=[];score=0}});requestAnimationFrame(loop)}loop()</script></body></html>`}

await ensureFolders();
const manifestFile = path.join(PUBLIC_DIR, 'games.json');
const manifest = Array.isArray(await readJson(manifestFile, [])) ? await readJson(manifestFile, []) : [];
const engine = chooseEngine(manifest);
const c = cfg(engine, manifest);
const html = engine.maker(c);
const errors = validateGameHtml(html);
if (errors.length) {
  await fs.writeFile(path.join(AUTO_DIR, 'debug-invalid-game.html'), html, 'utf8');
  throw new Error(errors.join(' | '));
}
const run = timeId();
const slug = `${run}-${slugify(engine.id)}-${seeded(c.seed, 100, 999)}`;
const dir = path.join(GAMES_DIR, slug);
await fs.mkdir(dir, { recursive: true });
await fs.writeFile(path.join(dir, 'index.html'), html, 'utf8');

const entry = {
  title: c.title,
  slug,
  description: `${c.genre} game in ${c.world}. V7 uses a separate game template, not the same engine with a new skin.`,
  genre: c.genre,
  engineId: engine.id,
  date: isoDate(),
  createdAt: new Date().toISOString(),
  url: `games/${slug}/`,
  generatorModel: 'v7-not-same-local',
  uniqueCatalogSize: ENGINES.length
};
const updated = [entry, ...manifest.filter(g => g.slug !== slug)];
await writeJson(manifestFile, updated);
await writeJson(path.join(AUTO_DIR, 'latest-game.json'), entry);
await fs.writeFile(path.join(PUBLIC_DIR, '.nojekyll'), '', 'utf8');

const repoName = (process.env.GITHUB_REPOSITORY || '16464-4434/amit-daily-game-factory2').split('/').at(-1);
const owner = process.env.GITHUB_REPOSITORY_OWNER || '16464-4434';
const site = `https://${owner}.github.io/${repoName}`;
const cards = updated.map(g => `<a class="card" href="${escapeHtml(g.url)}"><b>${escapeHtml(g.genre || g.engineId)}</b><h2>${escapeHtml(g.title)}</h2><p>${escapeHtml(g.description)}</p><span>Play →</span></a>`).join('\n');
await fs.writeFile(path.join(PUBLIC_DIR, 'index.html'), `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Amit Game Factory V7</title><style>body{margin:0;background:#060814;color:white;font-family:Arial,sans-serif;padding:28px}h1{font-size:clamp(34px,7vw,82px);margin:0 0 8px}.hero{background:linear-gradient(135deg,#61f4ff22,#ffe36e18);border:1px solid #ffffff22;border-radius:28px;padding:28px;margin-bottom:24px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:18px}.card{color:white;text-decoration:none;background:linear-gradient(135deg,#ffffff14,#ffffff08);border:1px solid #ffffff22;border-radius:22px;padding:22px;min-height:170px}.card b{color:#61f4ff}.card span{font-weight:900;color:#ffe36e}</style></head><body><section class="hero"><h1>Amit Game Factory V7</h1><p>Real variety mode: every run chooses from ${ENGINES.length} different mini-game templates and avoids recent repeats.</p><p>${updated.length} games · ${new Set(updated.map(g => g.engineId)).size} engine types used</p></section><div class="grid">${cards}</div></body></html>`, 'utf8');
await fs.writeFile(path.join(PUBLIC_DIR, 'robots.txt'), `User-agent: *\nAllow: /\nSitemap: ${site}/sitemap.xml\n`, 'utf8');
await fs.writeFile(path.join(PUBLIC_DIR, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${site}/</loc></url>${updated.map(g => `<url><loc>${site}/${g.url}</loc></url>`).join('')}</urlset>`, 'utf8');
console.log(`Created ${entry.title} with engine ${engine.id}. Recent repeats are blocked until the catalog cycles.`);
