import fs from 'node:fs/promises';
import tls from 'node:tls';
import path from 'node:path';
import { PUBLIC_DIR, escapeHtml, readJson } from './common.mjs';
function env(n){const v=process.env[n]?.trim(); if(!v) throw new Error(`Missing ${n}`); return v;}
function enc(v){return `=?UTF-8?B?${Buffer.from(String(v),'utf8').toString('base64')}?=`}
function b64(v){return Buffer.from(v,'utf8').toString('base64').match(/.{1,76}/g)?.join('\r\n')||''}
function dot(v){return v.replace(/\r?\n/g,'\r\n').replace(/^\./gm,'..')}
class SMTP{constructor(){this.s=tls.connect({host:'smtp.gmail.com',port:465,servername:'smtp.gmail.com',minVersion:'TLSv1.2'});this.buf='';this.q=[];this.s.setEncoding('utf8');this.s.on('data',c=>{this.buf+=c;this.flush()});this.s.on('error',e=>{while(this.q.length)this.q.shift().reject(e)})}async ready(){await new Promise((res,rej)=>{this.s.once('secureConnect',res);this.s.once('error',rej)});await this.read([220])}flush(){while(this.q.length){const m=this.buf.match(/^(?:\d{3}-.*\r?\n)*(\d{3}) [^\r\n]*(?:\r?\n|$)/m);if(!m)return;const raw=this.buf.slice(0,m.index+m[0].length);this.buf=this.buf.slice(m.index+m[0].length);const w=this.q.shift(),code=+m[1];w.expected.includes(code)?w.resolve(raw):w.reject(new Error(raw.trim()))}}read(expected){return new Promise((resolve,reject)=>{this.q.push({resolve,reject,expected});this.flush()})}cmd(c,e=[250]){this.s.write(c+'\r\n');return this.read(e)}async close(){try{await this.cmd('QUIT',[221])}catch{}this.s.end()}}
const user=env('GMAIL_USER'); const pass=env('GMAIL_APP_PASSWORD').replaceAll(' ',''); const to=process.env.EMAIL_TO?.trim()||user; const base=(process.env.DEPLOYED_SITE_URL||process.env.SITE_URL||'').trim().replace(/\/$/,''); if(!base) throw new Error('Missing DEPLOYED_SITE_URL or SITE_URL');
const manifest=await readJson(path.join(PUBLIC_DIR,'games.json'),[]); const latest=manifest[0]; if(!latest) throw new Error('No latest game');
const url=`${base}/${String(latest.url).replace(/^\/+/, '')}`; const subject=`🎮 משחק חדש: ${latest.title}`;
const text=`משחק חדש מוכן: ${latest.title}\n\n${url}\n\nגלריה: ${base}`;
const html=`<div style="font-family:Arial,sans-serif;background:#071020;color:white;padding:28px;border-radius:20px"><h1>${escapeHtml(latest.title)}</h1><p>${escapeHtml(latest.description)}</p><p><a href="${escapeHtml(url)}" style="background:#78f4ff;color:#071020;padding:14px 20px;border-radius:12px;text-decoration:none;font-weight:900">פתח משחק</a></p><p>גלריה: <a style="color:#ffe66e" href="${escapeHtml(base)}">${escapeHtml(base)}</a></p></div>`;
const boundary='amitv6'+Date.now(); const msg=[`From: ${enc('Amit Game Factory')} <${user}>`,`To: <${to}>`,`Subject: ${enc(subject)}`,'MIME-Version: 1.0',`Content-Type: multipart/alternative; boundary="${boundary}"`,'',`--${boundary}`,'Content-Type: text/plain; charset=UTF-8','Content-Transfer-Encoding: base64','',b64(text),`--${boundary}`,'Content-Type: text/html; charset=UTF-8','Content-Transfer-Encoding: base64','',b64(html),`--${boundary}--`,''].join('\r\n');
const s=new SMTP(); try{await s.ready();await s.cmd('EHLO github-actions');await s.cmd('AUTH LOGIN',[334]);await s.cmd(Buffer.from(user).toString('base64'),[334]);await s.cmd(Buffer.from(pass).toString('base64'),[235]);await s.cmd(`MAIL FROM:<${user}>`);await s.cmd(`RCPT TO:<${to}>`,[250,251]);await s.cmd('DATA',[354]);s.s.write(dot(msg)+'\r\n.\r\n');await s.read([250]);console.log('Email sent:',url)}finally{await s.close()}
